language: r
sudo: required
dist: trusty
#cache: packages
warnings_are_errors: false

apt_packages:
 - libgmp3-dev
 - libmpfr-dev
 
#r_binary_packages:
#  - Bessel
#  - testthat
#  - knitr
#  - rmarkdown
#  - covr

jobs:
  include:
  - r: devel
  - r: release
  
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
