# Sample .travis.yml for R projects

language: r
warnings_are_errors: false
sudo: required

r_binary_packages:
  - testthat
  - knitr
  - Bessel

r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change